# Generated by Django 5.0.1 on 2024-04-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signin',
            table='admininfo',
        ),
    ]
