# Generated by Django 5.0.3 on 2024-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_signin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEmployee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joineddate', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('contact_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'new_emp',
            },
        ),
        migrations.RemoveField(
            model_name='signin',
            name='username',
        ),
    ]
