# Generated by Django 5.0 on 2024-04-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_newemployee_remove_signin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='Admin_email',
            new_name='email',
        ),
    ]
