# Generated by Django 5.0.1 on 2024-04-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_newemployee_date_of_birth_newemployee_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newemployee',
            old_name='address',
            new_name='empAddress',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='department',
            new_name='empDepartment',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='designation',
            new_name='empDesignation',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='email',
            new_name='empEmail',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='emp_id',
            new_name='empId',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='image',
            new_name='empImg',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='joineddate',
            new_name='empJoindate',
        ),
        migrations.RenameField(
            model_name='newemployee',
            old_name='empname',
            new_name='empName',
        ),
    ]
