# Generated by Django 5.0.1 on 2024-04-25 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_address_newemployee_empaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newemployee',
            old_name='contact_number',
            new_name='empMobileno',
        ),
    ]
