# Generated by Django 5.0.1 on 2024-06-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
